### ISSUE TITLE
Extract to file failed

### ISSUE THREAD

**Issue by mirosval** [fannheyward/coc-react-refactor#37]
Thank you for this extension! 

I'm trying to use it, but I keep getting `Extract to file failed`. Any idea why that might be? I have also seen `E21 cannot make changes modifiable is off` I turned it on with `:set ma` but that didn't seem to do the trick.

**Comment by fannheyward** [comment]
Set `"coc.preferences.promptInput": false` in your coc-settings.json to fix this for now.

This is a coc bug. https://github.com/neoclide/coc.nvim/issues/2582

**Comment by fannheyward** [comment]
Fixed on latest coc.nvim, please upgrade it.
